### ISSUE TITLE
Double tap to play/pause is buggy

### ISSUE THREAD

**Issue by jamestong420** [marlboro-advance/mpvEx#169]
**Describe the bug
When i paly a video and double tap to pause it works the first time but the second time it doesn't do anything it does not play the video it stays pause until i click on the play button 

**Expected behavior**
Double should work every time as intended 

**Screenshots**/**Logs**
If applicable, add Screenshots/Logs to help explain your problem.

**Device Info (please complete the following information):**
 - OPPO A16
 - COLOR OS
 - Version 12

**Additional context**

**Comment by a20055** [comment]
自定义按键也是只能点一次

**Comment by marlboro-advance** [comment]
Fixed

**Comment by jamestong420** [comment]
I have tried on the latest preview build version 1.2.0 preview2 Double tap to play/pause is still buggy not fixed i have send u a screen recording of me double taping multiple times but it's not working
