### ISSUE TITLE
Can not connect to SMB local folder

### ISSUE THREAD

**Issue by kjllmeplz** [marlboro-advance/mpvEx#71]
**Describe the bug**
Can not connect to a SMB local folder in Anonymous or using account, other apps and player just connect fine.

**Screenshots**/**Logs**

<img width="3200" height="2136" alt="Image" src="https://github.com/user-attachments/assets/ecea4aac-1898-4bef-8b3f-753c195634f0" />

<img width="3200" height="2136" alt="Image" src="https://github.com/user-attachments/assets/591fda66-3ad1-49b1-9d7d-5b321ae02549" />

[mpvex_logs.txt](https://github.com/user-attachments/files/23655826/mpvex_logs.txt)

**Device Info (please complete the following information):**
 - Device Xiaomi Pad 8
 - Version android 16

**Comment by marlboro-advance** [comment]
This issue has been fixed in latest [preview builds](https://marlboro-advance.github.io/mpvEx/)

Let me know if it works

**Comment by kjllmeplz** [comment]
@marlboro-advance As you see on the logs, I'm using the lastest preview r26 and still facing this isssue. :(
